// <auto-generated />
using System;
using BookingsAssistant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingsAssistant.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202090332_AddOsmOAuthSupport")]
    partial class AddOsmOAuthSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ApplicationLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsmBookingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EmailMessageId");

                    b.HasIndex("OsmBookingId");

                    b.ToTable("ApplicationLinks");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office365AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Office365Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Office365RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Office365TokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OsmTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtractedBookingRef")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExtractedBookingRef");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmBookingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerEmail");

                    b.HasIndex("OsmBookingId")
                        .IsUnique();

                    b.ToTable("OsmBookings");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmBookingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmCommentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPreview")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsmBookingId");

                    b.HasIndex("OsmCommentId")
                        .IsUnique();

                    b.ToTable("OsmComments");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ApplicationLink", b =>
                {
                    b.HasOne("BookingsAssistant.Api.Data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("BookingsAssistant.Api.Data.Entities.EmailMessage", "EmailMessage")
                        .WithMany("Links")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingsAssistant.Api.Data.Entities.OsmBooking", "OsmBooking")
                        .WithMany("Links")
                        .HasForeignKey("OsmBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("EmailMessage");

                    b.Navigation("OsmBooking");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmComment", b =>
                {
                    b.HasOne("BookingsAssistant.Api.Data.Entities.OsmBooking", "Booking")
                        .WithMany("Comments")
                        .HasForeignKey("OsmBookingId")
                        .HasPrincipalKey("OsmBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.EmailMessage", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmBooking", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
