// <auto-generated />
using System;
using BookingsAssistant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingsAssistant.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720091242_AddProposedPlanExecutionResultJson")]
    partial class AddProposedPlanExecutionResultJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OsmTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmUsername")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GateCodeSentAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmBookingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsmBookingId")
                        .IsUnique();

                    b.ToTable("OsmBookings");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetched")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmBookingId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmCommentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextPreview")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsmBookingId");

                    b.HasIndex("OsmCommentId")
                        .IsUnique();

                    b.ToTable("OsmComments");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ProposedPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsmBookingId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEmailText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OsmBookingId");

                    b.ToTable("ProposedPlans");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.SiteDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteDuties");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmComment", b =>
                {
                    b.HasOne("BookingsAssistant.Api.Data.Entities.OsmBooking", "Booking")
                        .WithMany("Comments")
                        .HasForeignKey("OsmBookingId")
                        .HasPrincipalKey("OsmBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.ProposedPlan", b =>
                {
                    b.HasOne("BookingsAssistant.Api.Data.Entities.OsmBooking", "Booking")
                        .WithMany()
                        .HasForeignKey("OsmBookingId")
                        .HasPrincipalKey("OsmBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("BookingsAssistant.Api.Data.Entities.OsmBooking", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
