name: Bookings Assistant
version: 0.12.0
slug: bookings-assistant
description: Manage scout campsite bookings from OSM
url: https://github.com/piers-williams/bookings-helper
arch:
  - amd64
webui: https://[HOST]:[PORT:8099]/
ports:
  5000/tcp: 8099
ports_description:
  5000/tcp: Web interface
map:
  - data:rw
  - ssl:ro
options:
  osm_base_url: "https://www.onlinescoutmanager.co.uk"
  osm_campsite_id: "219"
  osm_section_id: "56710"
  osm_client_id: ""
  osm_client_secret: ""
  gate_code_days_before: 2
  gate_code_campaign_id: "123054"
  gate_code_from_name: ""
  gate_code_from_email: ""
  gate_code_subject: "Gate code"
  api_token: ""
  open_webui_base_url: ""
  open_webui_api_key: ""
  open_webui_model: ""
schema:
  osm_base_url: url
  osm_campsite_id: str
  osm_section_id: str
  osm_client_id: str
  osm_client_secret: password
  gate_code_days_before: "int(1,14)"
  gate_code_campaign_id: str
  gate_code_from_name: str
  gate_code_from_email: email
  gate_code_subject: str
  api_token: password
  open_webui_base_url: url
  open_webui_api_key: password
  open_webui_model: str
image: ghcr.io/piers-williams/bookings-assistant-{arch}
